// Realistic inputs with a note in brackets, the kind, and what a reasonable person expects (a test on the pick's
// label "name (disambiguation)"), written before looking at Qloo's answers; those were recorded live on 2026-10-04
// (test/note-fixtures.json: the search for the whole text and for the name before the note). Shared by Newcomer
// and Booker.
const starts = (s) => (l) => l.toLowerCase().startsWith(s.toLowerCase());
const has = (...ss) => (l) => ss.every((s) => l.toLowerCase().includes(s.toLowerCase()));
const none = (l) => l === "none";
const title = (t) => (l) => l.toLowerCase() === t.toLowerCase() || l.toLowerCase().startsWith(`${t} (`.toLowerCase()); // that exact title
const only = (name) => (l) => l.toLowerCase() === name.toLowerCase() || l.toLowerCase().startsWith(`${name} (`.toLowerCase()); // that name, any year
const at = (name, year) => (l) => l.toLowerCase().startsWith(`${name} (${year}`.toLowerCase()); // that title, that year
export const T = [
  // qualifiers: the note describes the thing
  ["Succession (TV series)", "tv_show", (l) => /^succession \(2018/i.test(l)],
  ["Dune (2021 film)", "movie", (l) => /^dune \(2021\)$/i.test(l)],
  ["Wednesday (indie rock band)", "artist", (l) => /^wednesday( \(|$)/i.test(l)],
  ["Taylor Swift (singer)", "artist", only("Taylor Swift")],
  ["Radiohead (band)", "artist", only("Radiohead")],
  ["Adele (singer)", "artist", only("Adele")],
  ["The Killers (band)", "artist", only("The Killers")],
  ["Prince (musician)", "artist", (l) => /^prince( \(|$)/i.test(l)],
  ["Phoebe Bridgers (singer-songwriter)", "artist", only("Phoebe Bridgers")],
  ["Big Thief (Adrianne Lenker)", "artist", only("Big Thief")],
  ["Breaking Bad (TV show)", "tv_show", only("Breaking Bad")],
  ["Fleabag (Amazon)", "tv_show", only("Fleabag")],
  ["The Bear (FX)", "tv_show", at("the bear", "2022")],
  ["Wednesday (Netflix series)", "tv_show", at("wednesday", "2022")],
  ["Shrinking (Apple TV+)", "tv_show", only("Shrinking")],
  ["The Office (US)", "tv_show", at("the office", "2005")],
  ["The Office (UK)", "tv_show", at("the office", "2001")],
  ["Parasite (2019)", "movie", at("parasite", "2019")],
  ["The Matrix (1999)", "movie", at("the matrix", "1999")],
  ["Arrival (2016 film)", "movie", at("arrival", "2016")],
  ["Avatar (2009)", "movie", at("avatar", "2009")],
  ["Interstellar (Christopher Nolan)", "movie", at("interstellar", "2014")],
  ["Dune (Denis Villeneuve)", "movie", at("dune", "2021")],
  // subtitles: the note is part of the title
  ["Star Wars (The Empire Strikes Back)", "movie", title("Star Wars: Episode V - The Empire Strikes Back")],
  ["Star Wars (Return of the Jedi)", "movie", title("Star Wars: Episode VI - Return of the Jedi")],
  ["Harry Potter (Prisoner of Azkaban)", "movie", title("Harry Potter and the Prisoner of Azkaban")],
  ["Lord of the Rings (Return of the King)", "movie", title("The Lord of the Rings: The Return of the King")],
  ["Dune (Part Two)", "movie", title("Dune: Part Two")],
  ["Dune (Part One)", "movie", at("dune", "2021")],
  ["The Godfather (Part II)", "movie", title("The Godfather Part II")],
  ["The Godfather (Part I)", "movie", (l) => /godfather/i.test(l) && /1972/.test(l)],
  ["Star Trek (The Original Series)", "tv_show", (l) => /^star trek( \(|$)/i.test(l)],
  ["Star Trek (The Next Generation)", "tv_show", title("Star Trek: The Next Generation")],
  ["Parts Unknown (Anthony Bourdain)", "tv_show", title("Anthony Bourdain: Parts Unknown")],
  ["No Reservations (Anthony Bourdain)", "tv_show", title("Anthony Bourdain: No Reservations")],
  // another name for it
  ["Yasiin Bey (Mos Def)", "artist", (l) => /^(mos def|yasiin bey)( \(|$)/i.test(l) && !/marvin/i.test(l)],
  ["Mos Def (Yasiin Bey)", "artist", (l) => /^(mos def|yasiin bey)( \(|$)/i.test(l) && !/marvin/i.test(l)],
  ["Ye (Kanye West)", "artist", none], // policy (pass 5): never another name for an act; see rankNames
  ["Cat Stevens (Yusuf)", "artist", (l) => /^(cat stevens|yusuf)/i.test(l)],
  ["Snoop Lion (Snoop Dogg)", "artist", (l) => /^(snoop dogg|snoop lion)( \(|$)/i.test(l)],
  ["La Casa de Papel (Money Heist)", "tv_show", only("Money Heist")],
  // nothing real
  ["Moonsprout (indie rock band)", "artist", none],
  ["Nobody Real Qzx (TV series)", "tv_show", none],
  // pass 4 (written before recording): a note word that is also a name ("band" -> The Band), a note already in the
  // name, a year that names a different entry than the plain title
  ["Wednesday (band)", "artist", (l) => /^wednesday( \(|$)/i.test(l)],
  ["Moonsprout (band)", "artist", none],
  ["Chance the Rapper (rapper)", "artist", only("Chance the Rapper")],
  ["Band of Horses (band)", "artist", only("Band of Horses")],
  ["Zac Brown Band (band)", "artist", only("Zac Brown Band")],
  ["Kendrick Lamar (rapper)", "artist", only("Kendrick Lamar")],
  ["Drake (rapper)", "artist", (l) => /^drake( \(|$)/i.test(l)],
  ["Arctic Monkeys (band)", "artist", only("Arctic Monkeys")],
  ["Bon Iver (band)", "artist", only("Bon Iver")],
  ["The Band (group)", "artist", (l) => /^the band( \(|$)/i.test(l)],
  ["The Lord of the Rings (2001)", "movie", title("The Lord of the Rings: The Fellowship of the Ring")],
  ["The Lion King (1994)", "movie", at("the lion king", "1994")],
  ["The Lion King (2019)", "movie", at("the lion king", "2019")],
  ["Little Women (2019)", "movie", at("little women", "2019")],
  ["The Batman (2022)", "movie", at("the batman", "2022")],
  ["Batman (1989)", "movie", at("batman", "1989")],
  ["Spider-Man (2002)", "movie", at("spider-man", "2002")],
  ["Dune (1984)", "movie", at("dune", "1984")],
  ["Fargo (TV series)", "tv_show", only("Fargo")],
  ["The Office (2005)", "tv_show", at("the office", "2005")],
  // pass 5 (written before recording): a person in the note, kind words inside titles, a fragment with the year,
  // a hometown, abbreviations
  ["Interstellar (Nolan)", "movie", at("interstellar", "2014")],
  ["Inception (Nolan)", "movie", at("inception", "2010")],
  ["Oppenheimer (Nolan)", "movie", at("oppenheimer", "2023")],
  ["Batman (movie)", "movie", (l) => /^batman( \(|$)/i.test(l)],
  ["Barbie (movie)", "movie", at("barbie", "2023")],
  ["Frozen (movie)", "movie", at("frozen", "2013")],
  ["Toy Story (Pixar)", "movie", at("toy story", "1995")],
  ["Spider-Man (2002 film)", "movie", (l) => /^spider-man \(2002\)$/i.test(l)],
  ["Moonsprout (Chicago)", "artist", none],
  ["Moonsprout (Boston)", "artist", none],
  ["Wilco (Chicago)", "artist", only("Wilco")],
  ["Phish (Vermont)", "artist", only("Phish")],
  ["The National (Cincinnati)", "artist", (l) => /^the national( \(|$)/i.test(l)],
  ["The Godfather (Pt. II)", "movie", title("The Godfather Part II")],
  ["Dune (Pt. 2)", "movie", title("Dune: Part Two")],
  ["Guardians of the Galaxy (Vol. 3)", "movie", title("Guardians of the Galaxy Vol. 3")],
  ["Guardians of the Galaxy (Volume 3)", "movie", title("Guardians of the Galaxy Vol. 3")],
  ["Kill Bill (Vol. 1)", "movie", (l) => /^kill bill:? vol(\.|ume) 1( \(|$)/i.test(l)],
  // pass 6 (written before recording): Roman numerals, a note naming one film of a series
  ["Star Wars (Episode 5)", "movie", title("Star Wars: Episode V - The Empire Strikes Back")],
  ["Star Wars (Episode 6)", "movie", title("Star Wars: Episode VI - Return of the Jedi")],
  ["Star Wars (Episode V)", "movie", title("Star Wars: Episode V - The Empire Strikes Back")],
  ["Harry Potter (Deathly Hallows Part I)", "movie", title("Harry Potter and the Deathly Hallows: Part 1")],
  ["The Hunger Games (Mockingjay Part I)", "movie", title("The Hunger Games: Mockingjay - Part 1")],
  ["Rocky (Rocky IV)", "movie", (l) => /^rocky iv( \(|$)/i.test(l)],
  ["Toy Story (Toy Story 3)", "movie", (l) => /^toy story 3( \(|$)/i.test(l)],
  ["Indiana Jones (Raiders of the Lost Ark)", "movie", title("Raiders of the Lost Ark")],
  // "Fast Five" adds only a number to the name's words, so it's a sequel, as "Toy Story (Toy Story 3)" (pass 17; pass 8
  // had made it the 2009 film); "Chicago P.D. (Chicago Fire)" adds a word, so there the exact name wins.
  ["Fast & Furious (Fast Five)", "movie", title("Fast Five")],
  ["Mission: Impossible (Fallout)", "movie", title("Mission: Impossible - Fallout")],
  ["The Matrix (Reloaded)", "movie", title("The Matrix Reloaded")],
  ["Pirates of the Caribbean (Dead Man's Chest)", "movie", title("Pirates of the Caribbean: Dead Man's Chest")],
  // pass 7 (written before recording): spin-offs whose note names the parent title
  ["Better Call Saul (Breaking Bad)", "tv_show", only("Better Call Saul")],
  ["Fear the Walking Dead (The Walking Dead)", "tv_show", only("Fear the Walking Dead")],
  ["House of the Dragon (Game of Thrones)", "tv_show", only("House of the Dragon")],
  ["The Mandalorian (Star Wars)", "tv_show", only("The Mandalorian")],
  ["Andor (Star Wars)", "tv_show", only("Andor")],
  ["Frasier (Cheers)", "tv_show", at("frasier", "1993")],
  ["Rogue One (Star Wars)", "movie", title("Rogue One: A Star Wars Story")],
  ["Logan (X-Men)", "movie", at("logan", "2017")],
  ["Venom (Spider-Man)", "movie", at("venom", "2018")],
  ["Serial (This American Life)", "podcast", only("Serial")],
  // pass 8 (written before recording): titles that lead with the subtitle; spin-offs sharing words with the parent
  ["Fast & Furious (Tokyo Drift)", "movie", title("The Fast and the Furious: Tokyo Drift")],
  ["Jurassic Park (The Lost World)", "movie", title("The Lost World: Jurassic Park")],
  ["Planet of the Apes (Rise)", "movie", title("Rise of the Planet of the Apes")],
  ["Star Wars (Rogue One)", "movie", title("Rogue One: A Star Wars Story")],
  ["Spider-Man (Homecoming)", "movie", title("Spider-Man: Homecoming")],
  ["Mad Max (Fury Road)", "movie", title("Mad Max: Fury Road")],
  ["Fuller House (Full House)", "tv_show", only("Fuller House")],
  ["Girl Meets World (Boy Meets World)", "tv_show", only("Girl Meets World")],
  ["That '90s Show (That '70s Show)", "tv_show", title("That '90s Show")],
  ["Chicago P.D. (Chicago Fire)", "tv_show", title("Chicago P.D.")],
  // pass 9 (written before recording): titles linked by "for"/"from", a note that is a fuller name, a typo in the name
  ["Planet of the Apes (War)", "movie", title("War for the Planet of the Apes")],
  ["Planet of the Apes (Escape)", "movie", title("Escape from the Planet of the Apes")],
  ["Whitney (Whitney Houston)", "movie", at("whitney", "2018")],
  ["Amy (Amy Winehouse)", "movie", at("amy", "2015")],
  ["Senna (Ayrton Senna)", "movie", at("senna", "2010")],
  ["Batman (The Dark Knight)", "movie", at("batman", "1989")], // policy: the exact name wins, The Dark Knight offered
  ["Better Call Saull (Breaking Bad)", "tv_show", only("Better Call Saul")],
  ["Fuller Hous (Full House)", "tv_show", only("Fuller House")],
  // pass 10 (written before recording): "aka" notes, surname-only notes, a spin-off titled "Note: A Name Saga",
  // sequel notes with Vol./Part
  ["La Casa de Papel (aka Money Heist)", "tv_show", only("Money Heist")],
  ["La Casa de Papel (a.k.a. Money Heist)", "tv_show", only("Money Heist")],
  ["Ye (aka Kanye West)", "artist", only("Kanye West")], // "aka" says it's another name, so an act may take it
  ["Amy (Winehouse documentary)", "movie", at("amy", "2015")],
  ["Whitney (Houston documentary)", "movie", at("whitney", "2018")],
  ["Mad Max (Furiosa)", "movie", title("Furiosa: A Mad Max Saga")],
  ["Guardians of the Galaxy (Guardians of the Galaxy Vol. 3)", "movie", title("Guardians of the Galaxy Vol. 3")],
  ["The Hunger Games (The Hunger Games: Mockingjay Part 1)", "movie", title("The Hunger Games: Mockingjay - Part 1")],
  ["The Godfather (The Godfather Part II)", "movie", title("The Godfather Part II")],
  // pass 11 (written before recording): names holding linking words, "Name Presents: Note", part words not in the title
  ["Back to the Future (Part 2)", "movie", (l) => /^back to the future part ii( \(|$)/i.test(l)],
  ["Back to the Future (Part 3)", "movie", (l) => /^back to the future part iii( \(|$)/i.test(l)],
  ["Men in Black (2)", "movie", (l) => /^men in black (ii|2)( \(|$)/i.test(l)],
  ["Men in Black (III)", "movie", (l) => /^men in black (iii|3)( \(|$)/i.test(l)],
  ["How to Train Your Dragon (Hidden World)", "movie", title("How to Train Your Dragon: The Hidden World")],
  ["A Nightmare on Elm Street (Dream Warriors)", "movie", title("A Nightmare on Elm Street 3: Dream Warriors")],
  ["Night at the Museum (Smithsonian)", "movie", title("Night at the Museum: Battle of the Smithsonian")],
  ["Fast & Furious (Hobbs & Shaw)", "movie", title("Fast & Furious Presents: Hobbs & Shaw")],
  ["Toy Story (Part 3)", "movie", (l) => /^toy story 3( \(|$)/i.test(l)],
  ["Frozen (Part 2)", "movie", (l) => /^frozen (ii|2)( \(|$)/i.test(l)],
  ["Kill Bill (Part 2)", "movie", (l) => /^kill bill:? vol(\.|ume) 2( \(|$)/i.test(l)],
  // pass 12 (written before recording): kind words that hide titles, a franchise word before the separator, Episode I
  ["SpongeBob (movie)", "movie", (l) => /^the spongebob (squarepants )?movie/i.test(l)],
  ["Jackass (movie)", "movie", title("Jackass: The Movie")],
  ["Twilight (New Moon)", "movie", title("The Twilight Saga: New Moon")],
  ["Twilight (Eclipse)", "movie", title("The Twilight Saga: Eclipse")],
  ["Twilight (Breaking Dawn Part 2)", "movie", title("The Twilight Saga: Breaking Dawn - Part 2")],
  ["Star Wars (Episode One)", "movie", title("Star Wars: Episode I - The Phantom Menace")],
  ["Star Wars (Episode 1)", "movie", title("Star Wars: Episode I - The Phantom Menace")],
  ["Star Wars (Episode I)", "movie", title("Star Wars: Episode I - The Phantom Menace")],
  // pass 13 (written before recording): a kind word inside a note naming a title; a bare number as the note
  ["Indiana Jones (Raiders of the Lost Ark film)", "movie", title("Raiders of the Lost Ark")],
  ["La Casa de Papel (Money Heist series)", "tv_show", only("Money Heist")],
  ["Mad Max (Furiosa movie)", "movie", title("Furiosa: A Mad Max Saga")],
  ["Planet of the Apes (War film)", "movie", title("War for the Planet of the Apes")],
  ["Jurassic Park (The Lost World film)", "movie", title("The Lost World: Jurassic Park")],
  ["Twilight (New Moon film)", "movie", title("The Twilight Saga: New Moon")],
  ["The Hunger Games (2)", "movie", title("The Hunger Games: Catching Fire")],
  ["Harry Potter (2)", "movie", title("Harry Potter and the Chamber of Secrets")],
  ["Kill Bill (2)", "movie", (l) => /^kill bill:? vol(\.|ume) 2( \(|$)/i.test(l)],
  ["Shrek (2)", "movie", title("Shrek 2")],
  ["Toy Story (2)", "movie", title("Toy Story 2")],
  ["Twilight (2)", "movie", title("The Twilight Saga: New Moon")],
  ["It (Chapter Two)", "movie", (l) => /^it:? chapter two( \(|$)/i.test(l)],
  // pass 14 (written before recording): number-only notes in series with other numbers, remakes, unnamed firsts
  ["Jurassic Park (2)", "movie", title("The Lost World: Jurassic Park")],
  ["Planet of the Apes (2)", "movie", title("Beneath the Planet of the Apes")],
  ["Mad Max (2)", "movie", (l) => /road warrior|^mad max 2/i.test(l)],
  ["Indiana Jones (2)", "movie", title("Indiana Jones and the Temple of Doom")],
  ["The Matrix (2)", "movie", title("The Matrix Reloaded")],
  // Known limit: Qloo holds an unrelated 1980 film titled "Alien 2: On Earth", which reads exactly like a sequel ("Shrek 2").
  ["Alien (2)", "movie", title("Aliens"), "an unrelated film is titled Alien 2"],
  ["Terminator (2)", "movie", title("Terminator 2: Judgment Day")],
  ["Die Hard (2)", "movie", title("Die Hard 2")],
  // pass 15 (written before recording): a number on a TV show is a season; the second Lord of the Rings; first films
  ["Skins (series 2)", "tv_show", at("skins", "2007")],
  ["Skins (season 2)", "tv_show", at("skins", "2007")],
  ["Fargo (series 2)", "tv_show", at("fargo", "2014")],
  ["The Bear (2)", "tv_show", at("the bear", "2022")],
  ["The Mandalorian (Season 2)", "tv_show", at("the mandalorian", "2019")],
  ["Stranger Things (Season 4)", "tv_show", only("Stranger Things")],
  ["The Lord of the Rings (2)", "movie", title("The Lord of the Rings: The Two Towers")],
  ["Die Hard (3)", "movie", title("Die Hard with a Vengeance")],
  ["Shrek (3)", "movie", title("Shrek the Third")],
  ["Toy Story (1)", "movie", at("toy story", "1995")],
  // pass 16 (written before recording): season notes next to companion shows and making-of specials; 2 Fast 2 Furious
  ["Stranger Things (Season 5)", "tv_show", only("Stranger Things")],
  ["Stranger Things (5)", "tv_show", only("Stranger Things")],
  ["Squid Game (Season 2)", "tv_show", only("Squid Game")],
  ["The Office (Season 3)", "tv_show", at("the office", "2005")],
  ["Breaking Bad (Season 5)", "tv_show", only("Breaking Bad")],
  ["The Fast and the Furious (2)", "movie", title("2 Fast 2 Furious")],
  // pass 17 (written before recording): a series that names its films inconsistently; numbers that work
  ["Fast & Furious (7)", "movie", title("Furious 7")],
  ["Fast & Furious (5)", "movie", title("Fast Five")],
  ["Fast & Furious (10)", "movie", title("Fast X")],
  ["Rambo (2)", "movie", (l) => /^rambo: first blood part ii( \(|$)/i.test(l)],
  ["Bad Boys (3)", "movie", (l) => /^bad boys for life( \(|$)/i.test(l)],
  ["Deadpool (3)", "movie", title("Deadpool & Wolverine")],
  // pass 18 (written before recording): a show's note holding a number that isn't a season; a name that is a numeral
  ["Drive to Survive (Formula 1)", "tv_show", title("Formula 1: Drive to Survive")],
  ["Drive to Survive (Formula One)", "tv_show", title("Formula 1: Drive to Survive")],
  ["X-Men (2)", "movie", (l) => /^x2\b/i.test(l)],
  ["Fantastic Four (2)", "movie", title("Fantastic Four: Rise of the Silver Surfer")],
  ["Knives Out (2)", "movie", (l) => /^glass onion/i.test(l)],
  // pass 19 (written before recording): the name's number typed as a digit
  ["Fantastic 4 (2)", "movie", title("Fantastic Four: Rise of the Silver Surfer")],
  ["Fantastic 4 (II)", "movie", title("Fantastic Four: Rise of the Silver Surfer")],
  // pass 20 (written before recording): long series where some films number themselves and others don't
  ["Mission: Impossible (7)", "movie", (l) => /^mission: impossible - dead reckoning/i.test(l)],
  ["Mission: Impossible (4)", "movie", title("Mission: Impossible - Ghost Protocol")],
  ["Fast & Furious (3)", "movie", title("The Fast and the Furious: Tokyo Drift")],
  ["Rocky (5)", "movie", title("Rocky V")],
  ["Twister (2)", "movie", title("Twisters")],
  ["Top Gun (2)", "movie", title("Top Gun: Maverick")],
  ["Batman (2)", "movie", title("Batman Returns"), "Qloo's searches never return Batman Returns"],
  ["Harry Potter (7)", "movie", title("Harry Potter and the Deathly Hallows: Part 1"), "Qloo's searches never return Deathly Hallows: Part 1"],
  ["The Hunger Games (4)", "movie", title("The Hunger Games: Mockingjay - Part 2")],
  ["Superman (2)", "movie", (l) => /^superman ii( \(|$)/i.test(l)],
  ["The Hunger Games (3)", "movie", title("The Hunger Games: Mockingjay - Part 1")],
  ["Harry Potter (8)", "movie", title("Harry Potter and the Deathly Hallows: Part 2")],
  ["Twilight (4)", "movie", title("The Twilight Saga: Breaking Dawn - Part 1"), "Qloo's top answer is Breaking Dawn - Part 2, and Eclipse is never returned"],
  ["Twilight (5)", "movie", title("The Twilight Saga: Breaking Dawn - Part 2")],
  // pass 21 (written before recording): a series where Qloo's top answer is always the last part
  ["Harry Potter (3)", "movie", title("Harry Potter and the Prisoner of Azkaban")],
  ["Harry Potter (4)", "movie", title("Harry Potter and the Goblet of Fire")],
  ["Twilight (3)", "movie", title("The Twilight Saga: Eclipse")],
  ["Dune (3)", "movie", title("Dune: Part Three")],
  // pass 22 (written before recording): a spelled-out number inside a title ("the Five Armies"); an older same-named film
  ["The Hobbit (3)", "movie", title("The Hobbit: The Battle of the Five Armies"), "an older film named exactly The Hobbit (1977) starts the count, and Qloo's top answer is Toy Story 3"],
  ["The Hobbit (2)", "movie", title("The Hobbit: The Desolation of Smaug")],
  ["The Hobbit (1)", "movie", title("The Hobbit: An Unexpected Journey"), "an older film named exactly The Hobbit (1977) is the first by the count"],
  ["Mission: Impossible (6)", "movie", title("Mission: Impossible - Fallout")],
  // pass 23 (written before recording): a note repeating the series name before a separator; a possessive in the title
  ["Mad Max (Mad Max: Fury Road)", "movie", title("Mad Max: Fury Road")],
  ["Mission: Impossible (Mission: Impossible - Fallout)", "movie", title("Mission: Impossible - Fallout")],
  ["Star Trek (Star Trek: The Next Generation)", "tv_show", title("Star Trek: The Next Generation")],
  ["Hardcore History (Dan Carlin)", "podcast", title("Dan Carlin's Hardcore History")],
  ["Poirot (Agatha Christie)", "tv_show", at("poirot", "1989")], // Qloo names the show plain "Poirot" (my expected title was wrong)
  // pass 24 (written before recording): a fuller name after a linking word; a note repeating the name before a subtitle;
  // a note naming part one; ordinal notes
  ["Alexander (Alexander the Great)", "movie", at("alexander", "2004")],
  ["Cyrano (Cyrano de Bergerac)", "movie", at("cyrano", "2021")],
  ["Twilight (Twilight: New Moon)", "movie", title("The Twilight Saga: New Moon")],
  ["Jurassic Park (Jurassic Park: The Lost World)", "movie", title("The Lost World: Jurassic Park")],
  ["Rambo (First Blood)", "movie", title("First Blood")],
  ["Shrek (2nd film)", "movie", title("Shrek 2")],
  ["Shrek (second film)", "movie", title("Shrek 2")],
  ["Toy Story (third film)", "movie", title("Toy Story 3")],
  ["The Matrix (second one)", "movie", title("The Matrix Reloaded")],
  // pass 25 (written before recording): ordinal notes searched as numbers; a note without its colon; a note that is the
  // full official title holding the name
  ["Mad Max (second film)", "movie", title("The Road Warrior")],
  ["The Matrix (the second one)", "movie", title("The Matrix Reloaded")],
  ["Star Trek (Star Trek The Next Generation)", "tv_show", title("Star Trek: The Next Generation")],
  ["Jurassic Park (The Lost World: Jurassic Park)", "movie", title("The Lost World: Jurassic Park")],
  ["Twilight (The Twilight Saga: New Moon)", "movie", title("The Twilight Saga: New Moon")],
  ["Mad Max (Furiosa: A Mad Max Saga)", "movie", title("Furiosa: A Mad Max Saga")],
  ["Planet of the Apes (Rise of the Planet of the Apes)", "movie", title("Rise of the Planet of the Apes")],
  // one-word notes on shows (a show may be named "Us")
  ["Shameless (US)", "tv_show", at("shameless", "2011")],
  ["House of Cards (US)", "tv_show", at("house of cards", "2013")],
  ["Skins (UK)", "tv_show", at("skins", "2007")],
  ["Queer as Folk (UK)", "tv_show", at("queer as folk", "1999")],
  ["Joker (Phoenix)", "movie", at("joker", "2019")],
  ["Her (Phoenix)", "movie", at("her", "2013")],
  ["Drive (Gosling)", "movie", at("drive", "2011")],
  // hometowns of acts Qloo doesn't know are never another name; real other names still work
  ["Moonsprout (New York)", "artist", none],
  ["Moonsprout (Los Angeles)", "artist", none],
  ["Moonsprout (Austin, TX)", "artist", none],
  ["Moonsprout (Brooklyn)", "artist", none],
  ["Moonsprout (Kansas City)", "artist", none],
  ["Moonsprout (New Orleans)", "artist", none],
  ["Moonsprout (San Francisco)", "artist", none],
  ["Moonsprout (Las Vegas)", "artist", none],
  ["Moonsprout (New England)", "artist", none],
  ["Puff Daddy (Diddy)", "artist", (l) => /^(diddy|puff daddy|p\. diddy|sean combs)/i.test(l)],
  ["Lady Gaga (Stefani Germanotta)", "artist", only("Lady Gaga")],
  // names that end in brackets themselves
  ["Birdman (or The Unexpected Virtue of Ignorance)", "movie", (l) => /^birdman or \(the unexpected virtue of ignorance\) \(2014/i.test(l)],
];
