// Realistic inputs with a note in brackets, the kind, and what a reasonable person expects (a test on the pick's
// label "name (disambiguation)"), written before looking at Qloo's answers; those were recorded live on 2026-10-04
// (test/note-fixtures.json: the search for the whole text and for the name before the note). Shared by Newcomer
// and Booker.
const starts = (s) => (l) => l.toLowerCase().startsWith(s.toLowerCase());
const has = (...ss) => (l) => ss.every((s) => l.toLowerCase().includes(s.toLowerCase()));
const none = (l) => l === "none";
const only = (name) => (l) => l.toLowerCase() === name.toLowerCase() || l.toLowerCase().startsWith(`${name} (`.toLowerCase()); // that name, any year
const at = (name, year) => (l) => l.toLowerCase().startsWith(`${name} (${year}`.toLowerCase()); // that title, that year
export const T = [
  // qualifiers: the note describes the thing
  ["Succession (TV series)", "tv_show", (l) => /^succession \(2018/i.test(l)],
  ["Dune (2021 film)", "movie", (l) => /^dune \(2021\)$/i.test(l)],
  ["Wednesday (indie rock band)", "artist", (l) => /^wednesday( \(|$)/i.test(l)],
  ["Taylor Swift (singer)", "artist", only("Taylor Swift")],
  ["Radiohead (band)", "artist", only("Radiohead")],
  ["Adele (singer)", "artist", only("Adele")],
  ["The Killers (band)", "artist", only("The Killers")],
  ["Prince (musician)", "artist", (l) => /^prince( \(|$)/i.test(l)],
  ["Phoebe Bridgers (singer-songwriter)", "artist", only("Phoebe Bridgers")],
  ["Big Thief (Adrianne Lenker)", "artist", only("Big Thief")],
  ["Breaking Bad (TV show)", "tv_show", only("Breaking Bad")],
  ["Fleabag (Amazon)", "tv_show", only("Fleabag")],
  ["The Bear (FX)", "tv_show", at("the bear", "2022")],
  ["Wednesday (Netflix series)", "tv_show", at("wednesday", "2022")],
  ["Shrinking (Apple TV+)", "tv_show", only("Shrinking")],
  ["The Office (US)", "tv_show", at("the office", "2005")],
  ["The Office (UK)", "tv_show", at("the office", "2001")],
  ["Parasite (2019)", "movie", at("parasite", "2019")],
  ["The Matrix (1999)", "movie", at("the matrix", "1999")],
  ["Arrival (2016 film)", "movie", at("arrival", "2016")],
  ["Avatar (2009)", "movie", at("avatar", "2009")],
  ["Interstellar (Christopher Nolan)", "movie", at("interstellar", "2014")],
  ["Dune (Denis Villeneuve)", "movie", at("dune", "2021")],
  // subtitles: the note is part of the title
  ["Star Wars (The Empire Strikes Back)", "movie", has("empire strikes back")],
  ["Star Wars (Return of the Jedi)", "movie", has("return of the jedi")],
  ["Harry Potter (Prisoner of Azkaban)", "movie", has("azkaban")],
  ["Lord of the Rings (Return of the King)", "movie", has("return of the king")],
  ["Dune (Part Two)", "movie", has("part two")],
  ["Dune (Part One)", "movie", at("dune", "2021")],
  ["The Godfather (Part II)", "movie", (l) => /godfather part ii( \(|$)/i.test(l)],
  ["The Godfather (Part I)", "movie", (l) => /godfather/i.test(l) && /1972/.test(l)],
  ["Star Trek (The Original Series)", "tv_show", (l) => /^star trek( \(|$)/i.test(l)],
  ["Star Trek (The Next Generation)", "tv_show", has("next generation")],
  ["Parts Unknown (Anthony Bourdain)", "tv_show", has("parts unknown")],
  ["No Reservations (Anthony Bourdain)", "tv_show", has("no reservations")],
  // another name for it
  ["Yasiin Bey (Mos Def)", "artist", (l) => /^(mos def|yasiin bey)( \(|$)/i.test(l) && !/marvin/i.test(l)],
  ["Mos Def (Yasiin Bey)", "artist", (l) => /^(mos def|yasiin bey)( \(|$)/i.test(l) && !/marvin/i.test(l)],
  ["Ye (Kanye West)", "artist", none], // policy (pass 5): never another name for an act; see rankNames
  ["Cat Stevens (Yusuf)", "artist", (l) => /^(cat stevens|yusuf)/i.test(l)],
  ["Snoop Lion (Snoop Dogg)", "artist", (l) => /^(snoop dogg|snoop lion)( \(|$)/i.test(l)],
  ["La Casa de Papel (Money Heist)", "tv_show", (l) => /money heist|casa de papel/i.test(l)],
  // nothing real
  ["Moonsprout (indie rock band)", "artist", none],
  ["Nobody Real Qzx (TV series)", "tv_show", none],
  // pass 4 (written before recording): a note word that is also a name ("band" -> The Band), a note already in the
  // name, a year that names a different entry than the plain title
  ["Wednesday (band)", "artist", (l) => /^wednesday( \(|$)/i.test(l)],
  ["Moonsprout (band)", "artist", none],
  ["Chance the Rapper (rapper)", "artist", only("Chance the Rapper")],
  ["Band of Horses (band)", "artist", only("Band of Horses")],
  ["Zac Brown Band (band)", "artist", only("Zac Brown Band")],
  ["Kendrick Lamar (rapper)", "artist", only("Kendrick Lamar")],
  ["Drake (rapper)", "artist", (l) => /^drake( \(|$)/i.test(l)],
  ["Arctic Monkeys (band)", "artist", only("Arctic Monkeys")],
  ["Bon Iver (band)", "artist", only("Bon Iver")],
  ["The Band (group)", "artist", (l) => /^the band( \(|$)/i.test(l)],
  ["The Lord of the Rings (2001)", "movie", has("fellowship")],
  ["The Lion King (1994)", "movie", at("the lion king", "1994")],
  ["The Lion King (2019)", "movie", at("the lion king", "2019")],
  ["Little Women (2019)", "movie", at("little women", "2019")],
  ["The Batman (2022)", "movie", at("the batman", "2022")],
  ["Batman (1989)", "movie", at("batman", "1989")],
  ["Spider-Man (2002)", "movie", at("spider-man", "2002")],
  ["Dune (1984)", "movie", at("dune", "1984")],
  ["Fargo (TV series)", "tv_show", only("Fargo")],
  ["The Office (2005)", "tv_show", at("the office", "2005")],
  // pass 5 (written before recording): a person in the note, kind words inside titles, a fragment with the year,
  // a hometown, abbreviations
  ["Interstellar (Nolan)", "movie", at("interstellar", "2014")],
  ["Inception (Nolan)", "movie", at("inception", "2010")],
  ["Oppenheimer (Nolan)", "movie", at("oppenheimer", "2023")],
  ["Batman (movie)", "movie", (l) => /^batman( \(|$)/i.test(l)],
  ["Barbie (movie)", "movie", at("barbie", "2023")],
  ["Frozen (movie)", "movie", at("frozen", "2013")],
  ["Toy Story (Pixar)", "movie", at("toy story", "1995")],
  ["Spider-Man (2002 film)", "movie", (l) => /^spider-man \(2002\)$/i.test(l)],
  ["Moonsprout (Chicago)", "artist", none],
  ["Moonsprout (Boston)", "artist", none],
  ["Wilco (Chicago)", "artist", only("Wilco")],
  ["Phish (Vermont)", "artist", only("Phish")],
  ["The National (Cincinnati)", "artist", (l) => /^the national( \(|$)/i.test(l)],
  ["The Godfather (Pt. II)", "movie", (l) => /godfather part ii( \(|$)/i.test(l)],
  ["Dune (Pt. 2)", "movie", has("part two")],
  ["Guardians of the Galaxy (Vol. 3)", "movie", (l) => /vol(\.|ume) 3/i.test(l)],
  ["Guardians of the Galaxy (Volume 3)", "movie", (l) => /vol(\.|ume) 3/i.test(l)],
  ["Kill Bill (Vol. 1)", "movie", (l) => /vol(\.|ume) 1/i.test(l)],
  // pass 6 (written before recording): Roman numerals, a note naming one film of a series
  ["Star Wars (Episode 5)", "movie", has("empire strikes back")],
  ["Star Wars (Episode 6)", "movie", has("return of the jedi")],
  ["Star Wars (Episode V)", "movie", has("empire strikes back")],
  ["Harry Potter (Deathly Hallows Part I)", "movie", (l) => /deathly hallows.*part 1\b/i.test(l)],
  ["The Hunger Games (Mockingjay Part I)", "movie", (l) => /mockingjay.*part 1\b/i.test(l)],
  ["Rocky (Rocky IV)", "movie", (l) => /^rocky iv( \(|$)/i.test(l)],
  ["Toy Story (Toy Story 3)", "movie", (l) => /^toy story 3( \(|$)/i.test(l)],
  ["Indiana Jones (Raiders of the Lost Ark)", "movie", (l) => /raiders of the lost ark/i.test(l)],
  // Policy (pass 8): an entry named exactly the name wins over a title named in the note, which is offered under
  // "Not it?" ("Chicago P.D. (Chicago Fire)" has the same shape and means Chicago P.D.).
  ["Fast & Furious (Fast Five)", "movie", at("fast & furious", "2009")],
  ["Mission: Impossible (Fallout)", "movie", (l) => /fallout/i.test(l)],
  ["The Matrix (Reloaded)", "movie", (l) => /reloaded/i.test(l)],
  ["Pirates of the Caribbean (Dead Man's Chest)", "movie", (l) => /dead man/i.test(l)],
  // pass 7 (written before recording): spin-offs whose note names the parent title
  ["Better Call Saul (Breaking Bad)", "tv_show", only("Better Call Saul")],
  ["Fear the Walking Dead (The Walking Dead)", "tv_show", only("Fear the Walking Dead")],
  ["House of the Dragon (Game of Thrones)", "tv_show", only("House of the Dragon")],
  ["The Mandalorian (Star Wars)", "tv_show", only("The Mandalorian")],
  ["Andor (Star Wars)", "tv_show", only("Andor")],
  ["Frasier (Cheers)", "tv_show", at("frasier", "1993")],
  ["Rogue One (Star Wars)", "movie", (l) => /^rogue one/i.test(l)],
  ["Logan (X-Men)", "movie", at("logan", "2017")],
  ["Venom (Spider-Man)", "movie", at("venom", "2018")],
  ["Serial (This American Life)", "podcast", only("Serial")],
  // pass 8 (written before recording): titles that lead with the subtitle; spin-offs sharing words with the parent
  ["Fast & Furious (Tokyo Drift)", "movie", (l) => /tokyo drift/i.test(l)],
  ["Jurassic Park (The Lost World)", "movie", (l) => /lost world/i.test(l)],
  ["Planet of the Apes (Rise)", "movie", (l) => /^rise of the planet of the apes/i.test(l)],
  ["Star Wars (Rogue One)", "movie", (l) => /^rogue one/i.test(l)],
  ["Spider-Man (Homecoming)", "movie", (l) => /^spider-man: homecoming/i.test(l)],
  ["Mad Max (Fury Road)", "movie", (l) => /^mad max: fury road/i.test(l)],
  ["Fuller House (Full House)", "tv_show", only("Fuller House")],
  ["Girl Meets World (Boy Meets World)", "tv_show", only("Girl Meets World")],
  ["That '90s Show (That '70s Show)", "tv_show", (l) => /^that '90s show/i.test(l)],
  ["Chicago P.D. (Chicago Fire)", "tv_show", (l) => /^chicago p\.?d/i.test(l)],
  // pass 9 (written before recording): titles linked by "for"/"from", a note that is a fuller name, a typo in the name
  ["Planet of the Apes (War)", "movie", (l) => /^war for the planet of the apes/i.test(l)],
  ["Planet of the Apes (Escape)", "movie", (l) => /^escape from the planet of the apes/i.test(l)],
  ["Whitney (Whitney Houston)", "movie", at("whitney", "2018")],
  ["Amy (Amy Winehouse)", "movie", at("amy", "2015")],
  ["Senna (Ayrton Senna)", "movie", at("senna", "2010")],
  ["Batman (The Dark Knight)", "movie", at("batman", "1989")], // policy: the exact name wins, The Dark Knight offered
  ["Better Call Saull (Breaking Bad)", "tv_show", only("Better Call Saul")],
  ["Fuller Hous (Full House)", "tv_show", only("Fuller House")],
  // one-word notes on shows (a show may be named "Us")
  ["Shameless (US)", "tv_show", at("shameless", "2011")],
  ["House of Cards (US)", "tv_show", at("house of cards", "2013")],
  ["Skins (UK)", "tv_show", at("skins", "2007")],
  ["Queer as Folk (UK)", "tv_show", at("queer as folk", "1999")],
  ["Joker (Phoenix)", "movie", at("joker", "2019")],
  ["Her (Phoenix)", "movie", at("her", "2013")],
  ["Drive (Gosling)", "movie", at("drive", "2011")],
  // hometowns of acts Qloo doesn't know are never another name; real other names still work
  ["Moonsprout (New York)", "artist", none],
  ["Moonsprout (Los Angeles)", "artist", none],
  ["Moonsprout (Austin, TX)", "artist", none],
  ["Moonsprout (Brooklyn)", "artist", none],
  ["Moonsprout (Kansas City)", "artist", none],
  ["Moonsprout (New Orleans)", "artist", none],
  ["Moonsprout (San Francisco)", "artist", none],
  ["Moonsprout (Las Vegas)", "artist", none],
  ["Moonsprout (New England)", "artist", none],
  ["Puff Daddy (Diddy)", "artist", (l) => /^(diddy|puff daddy|p\. diddy|sean combs)/i.test(l)],
  ["Lady Gaga (Stefani Germanotta)", "artist", only("Lady Gaga")],
  // names that end in brackets themselves
  ["Birdman (or The Unexpected Virtue of Ignorance)", "movie", (l) => /^birdman or \(the unexpected virtue of ignorance\) \(2014/i.test(l)],
];
